// Copyright (c) 2018 Gamecentric, All rights reserved

#include "GCFSMStateNode.h"
#include "GCFSMEditorModule.h"
#include "GCFSMStateFactory.h"
#include "GCFSM.h"
#include "GCFSMState.h"
#include "GCFSMLocalState.h"
#include "GCFSMSubmachineState.h"
#include "GCFSMUtilities.h"
#include "KismetCompiler.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_SwitchName.h"
#include "K2Node_MakeArray.h"
#include "KismetNodes/SGraphNodeK2Base.h"
#include "KismetNodes/KismetNodeInfoContext.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Kismet2/Kismet2NameValidators.h"
#include "AssetToolsModule.h"
#include "ScopedTransaction.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "SNameComboBox.h"
#include "Widgets/Images/SImage.h"
#include "Framework/MultiBox/MultiBoxBuilder.h"
#include "GCFSMLocalStateEntryPointNode.h"
#include "GCFSMEditorSettings.h"
#include "GCFSMEditorUtilities.h"
#include "GCFSMStartNode.h"
#include "EnumHelpers.h"
#include "Editor.h"
#include "ToolMenu.h"

#if ENGINE_MAJOR_VERSION ==	4 && ENGINE_MINOR_VERSION >= 24
#include "ToolMenus.h"
#endif

ENUM_HELPERS_NAME(EGCFSMSubmachineReplicationOptions, GCFSM);

#define LOCTEXT_NAMESPACE "GCFSM.StateNodes"

UGCFSMStateNode::UGCFSMStateNode(const FObjectInitializer& objectInitializer)
	: Super(objectInitializer)
{
	transitionEvents.Add("Event");

#if WITH_EDITORONLY_DATA
	bCanRenameNode = true;
#endif
}

void UGCFSMStateNode::Serialize(FArchive& ar)
{
	Super::Serialize(ar);

	// backward compatibility code
	if (ar.IsLoading() && localState_DEPRECATED)
	{
		localState_DEPRECATED = false;
		nodeKind = EGCFSMStateNodeKind::Local;
	}
}

void UGCFSMStateNode::AllocateDefaultPins()
{
	UGCFSMNodeBase::AllocateDefaultPins();

	auto schema = GetDefault<UEdGraphSchema_K2>();

	// Add the implementation pin (regular states only)
	check(Pins.Num() == ImplementationPinIndex);
	auto pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Class, {}, UGCFSMState::StaticClass(), "ImplementationClass");
	pin->PinFriendlyName = LOCTEXT("ImplementationPin", "Implementation Class");
	pin->PinToolTip = LOCTEXT("ImplementationPin.Tooltip", "A class that will be instantantied to handle this state logic").ToString();
	pin->bHidden = !IsRegularState();

	// Add the pin for replication option (submachine states only)
	check(Pins.Num() == ReplicationOptionPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, {}, EnumHelpers::GetUEnum<EGCFSMSubmachineReplicationOptions>(), "replication");
	pin->bHidden = !IsSubmachineState();
	schema->SetPinAutogeneratedDefaultValueBasedOnType(pin);

	// Add the hidden replicated exit pin
	check(Pins.Num() == ReplicatedExitPinIndex);
	pin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, {}, nullptr);
	pin->bHidden = true;

	// Add transition pins for each name
	check(Pins.Num() == TransitionsPinStartIndex);
	for (auto name : transitionEvents)
	{
		pin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, {}, nullptr, name);
		pin->PinToolTip = LOCTEXT("TransitionPin.Tooltip", "Transition pin\n").ToString() + name.ToString();
	}

	// Add the Timed Event pins
	pin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, {}, nullptr, GetTimeOutEventPinName());
	pin->PinToolTip = LOCTEXT("TimeOutEvent.Tooltip", "This transition is triggered after the timeout has expired").ToString();
	pin->bHidden = true;
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, nullptr, "TimeOut");
	pin->PinToolTip = LOCTEXT("TimeOut.Tooltip", "If greater than 0, the state is automatically exited after the specified time in seconds").ToString();
	pin->bHidden = true;
	schema->SetPinAutogeneratedDefaultValueBasedOnType(pin);
	SetTimedEvenPinFriendlyName();

	// Add the Tick pins
	pin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, {}, nullptr, GetTickPinName());
	pin->PinFriendlyName = FText::FromString(TEXT("Tick"));
	pin->PinToolTip = LOCTEXT("TickPin.Tooltip", "This pin is executed every frame while this state is active").ToString();
	pin->bHidden = true;
	pin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, nullptr, "DeltaTime");
	pin->PinToolTip = LOCTEXT("DeltaTimePin.Tooltip", "Delta time in seconds since the last Tick event. The value is valid only when the Tick pin is executed").ToString();
	pin->bHidden = true;
}

UEdGraphPin* UGCFSMStateNode::GetTimeOutEventPin() const
{
	return Pins[TransitionsPinStartIndex + transitionEvents.Num()];
}

UEdGraphPin* UGCFSMStateNode::GetTimeOutPin() const
{
	return Pins[TransitionsPinStartIndex + transitionEvents.Num() + 1];
}

UEdGraphPin* UGCFSMStateNode::GetTickPin() const
{
	return Pins[TransitionsPinStartIndex + transitionEvents.Num() + 2];
}

UEdGraphPin* UGCFSMStateNode::GetDeltaTimePin() const
{
	return Pins[TransitionsPinStartIndex + transitionEvents.Num() + 3];
}

UGCFSMStateNode::ERedirectType UGCFSMStateNode::DoPinsMatchForReconstruction(const UEdGraphPin* newPin, int32 newPinIndex, const UEdGraphPin* oldPin, int32 oldPinIndex) const
{
	// This check is to match pins whose name has been edited by the user
	if (newPinIndex == indexOfEventPinBeingRenamed && newPinIndex == oldPinIndex)
	{
		return ERedirectType::ERedirectType_Value;
	}
	else
	{
		return Super::DoPinsMatchForReconstruction(newPin, newPinIndex, oldPin, oldPinIndex);
	}
}

static void ShowPin(UEdGraphPin* pin, bool visible)
{
	if (pin->bHidden == visible)
	{
		pin->Modify();
		pin->bHidden = !visible;
	}

	if (!visible)
	{
		pin->BreakAllPinLinks();
	}
}

void UGCFSMStateNode::SetTimedEvenPinFriendlyName()
{
	auto eventPin = GetTimeOutEventPin();
	if (GetTimeOutPin()->LinkedTo.Num() > 0 || timeOut <= 0)
	{
		// timeout is unknown or invalid
		eventPin->PinFriendlyName = LOCTEXT("TimePinLabel.Dynamic", "After ?s");
	}
	else
	{
		// timeout is known
		auto str = FString::Printf(TEXT("%.2f"), timeOut);
		if (!str.RemoveFromEnd(".00"))
		{
			str.RemoveFromEnd("0");
		}
		FFormatNamedArguments args;
		args.Add(TEXT("Time"), FText::FromString(str));
		eventPin->PinFriendlyName = FText::Format(LOCTEXT("TimePinLabel.Static", "After {Time}s"), args);
	}
}

void UGCFSMStateNode::PostPlacedNewNode()
{
	Super::PostPlacedNewNode();
	SyncAllPins();
}

void UGCFSMStateNode::PostReconstructNode()
{
	// Show/hide optional pins
	SyncAllPins();
	ShowPin(GetTimeOutEventPin(), timeOut > 0 || GetTimeOutPin()->LinkedTo.Num());
	ShowPin(GetTickPin(), showTickFunction);
	ShowPin(GetDeltaTimePin(), showTickFunction);
	SetTimedEvenPinFriendlyName();

	Super::PostReconstructNode();

	// Reset these, reconstruction is finished
	indexOfEventPinBeingRenamed = -1;
	bReconstructNode = false;
}

void UGCFSMStateNode::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	if (propertyChangedEvent.Property)
	{
		SyncPinWithProperty(propertyChangedEvent.Property);

		FName propertyName = propertyChangedEvent.Property->GetFName();
		if (propertyName == "transitionEvents")
		{
			if (propertyChangedEvent.ChangeType == EPropertyChangeType::ValueSet)
			{
				// An event has been renamed, save the index so that we can properly match pins during reconstruction
				indexOfEventPinBeingRenamed = TransitionsPinStartIndex + propertyChangedEvent.GetArrayIndex("transitionEvents");
			}
		}

		if ((propertyChangedEvent.ChangeType & EPropertyChangeType::Interactive) == 0)
		{
			ReconstructNode();
		}
	}

	Super::PostEditChangeProperty(propertyChangedEvent);
}

TSharedPtr<INameValidatorInterface> UGCFSMStateNode::MakeNameValidator() const
{
	return MakeShared<FDummyNameValidator>(EValidatorResult::Ok);
}

void UGCFSMStateNode::OnRenameNode(const FString& newName)
{
	NodeName = (newName == GetDefaultTitle().ToString() || newName == SuggestedNodeName()) ? FString {} : newName;

	if (auto schema = GetSchema())
	{
		schema->ForceVisualizationCacheClear();
	}
}

bool UGCFSMStateNode::HasImplementationClass() const
{
	// the extra check about Pins.Num() is necessary, because this function might be called before allocating the pins
	return Pins.Num() && (Pins[ImplementationPinIndex]->DefaultObject || Pins[ImplementationPinIndex]->LinkedTo.Num() > 0);
}

UClass* UGCFSMStateNode::GetImplementationClass() const
{
	// the extra check about Pins.Num() is necessary, because this function might be called before allocating the pins
	return Pins.Num() && Pins[ImplementationPinIndex]->LinkedTo.Num() == 0 ? Cast<UClass>(Pins[ImplementationPinIndex]->DefaultObject) : nullptr;
}

UGCFSMStartNode* UGCFSMStateNode::GetSubmachineNode() const
{
	return UGCFSMStartNode::GetStartNodeFromGuid(GetBlueprint(), submachineNodeGuid);
}

FSlateIcon UGCFSMStateNode::GetIconAndTint(FLinearColor& outColor) const
{
	return FSlateIcon("GCFSM",
		IsLocalState() ? "NodeIcon.FSMLocalState" :
		IsSubmachineState() ? "NodeIcon.FSMSubmachineState" :
		HasImplementationClass() ? "NodeIcon.FSMState" :
		"NodeIcon.FSMBasicState");
}

FText UGCFSMStateNode::GetDefaultTitle() const
{
	return IsLocalState() ? LOCTEXT("DefaultTitle.Local", "FSM Local State") :
		IsSubmachineState() ? LOCTEXT("DefaultTitle.Submachine", "FSM Submachine State") :
		LOCTEXT("DefaultTitle", "FSM State");
}

FString UGCFSMStateNode::SuggestedNodeName() const
{
	if (IsLocalState())
	{
		auto graph = localImplementationGraph.GetGraph();
		if (IsValid(graph))
		{
			return graph->GetName();
		}
	}
	else if (IsSubmachineState())
	{
		auto node = GetSubmachineNode();
		return node ? node->GetFriendlyName() : FString {};
	}
	else if (auto implementationClass = GetImplementationClass())
	{
		return implementationClass->GetDisplayNameText().ToString();
	}
	return {};
}

FText UGCFSMStateNode::GetNodeTitle(ENodeTitleType::Type titleType) const
{
	FText defaultTitle = GetDefaultTitle();
	FString name = NodeName.Len() > 0 ? NodeName : SuggestedNodeName();
	if (name.Len() > 0)
	{
		if (titleType == ENodeTitleType::EditableTitle)
		{
			return FText::FromString(name);
		}
		else if (titleType == ENodeTitleType::FullTitle)
		{
			return FText::FromString(name + "\n" + defaultTitle.ToString());
		}
	}
	return defaultTitle;
}

FName UGCFSMStateNode::GetCornerIcon() const
{
	return "Graph.Latent.LatentIcon";
}

FText UGCFSMStateNode::GetToolTipHeading() const
{
	return FText::FromString(NodeName);
}

FText UGCFSMStateNode::GetTooltipText() const
{
	FTextBuilder builder;
	builder.AppendLine(GetDefaultTitle());
	builder.AppendLine();
	builder.AppendLine(LOCTEXT("Tooltip.Footer", "The FSM remains in this state until a transition event is triggered.\nDeferred events are kepts in queue to be processed by the next state."));
	if (IsLocalState())
	{
		builder.AppendLine(LOCTEXT("Tooltip.Footer.Local", "The Entry/Tick/Exit notifications are implemented in the specified graph of this object."));
	}
	else if (IsSubmachineState())
	{
		builder.AppendLine(LOCTEXT("Tooltip.Footer.Submachine", "Upon entering this state, the specified FSM is launched as a sub-FSM."));
	}
	else if (HasImplementationClass())
	{
		builder.AppendLine(LOCTEXT("Tooltip.Footer.WithClass", "A state object of the specified class is spawned, which will\nreceive Entry/Tick/Exit notifications and may process events internally."));
	}
	return builder.ToText();
}

void UGCFSMStateNode::ValidateNodeDuringCompilation(class FCompilerResultsLog& messageLog) const
{
	Super::ValidateNodeDuringCompilation(messageLog);

	// Make sure the node has as many labels as transition pins
	// Don't trust internal data: let's count them
	int numTransitionPins = 0;
	for (int i = TransitionsPinStartIndex; i < Pins.Num(); ++i, ++numTransitionPins)
	{
		auto pin = Pins[i];
		if (pin->Direction != EGPD_Output || pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec || IsTimeOutEventPin(pin) || IsTickPin(pin))
		{
			break;
		}
	}

	if (numTransitionPins != transitionEvents.Num())
	{
		messageLog.Error(TEXT("@@ number of event labels and transition pins mismatch"), this);
	}

	// Common test to check for duplicate names
	TSet<FName> allNames;
	auto checkDuplicates = [&](const FName& name)
	{
		bool duplicate;
		allNames.Add(name, &duplicate);
		if (duplicate)
		{
			messageLog.Error(*FString::Printf(TEXT("@@ has a duplicate event %s"), *name.ToString()), this);
		}
	};

	// Make sure all transition events are valid
	for (auto const& name : transitionEvents)
	{
		if (!name.IsValid() || name.IsNone() || name == UGCFSMBasicState::GetTickEventName() || name == UGCFSMBasicState::GetTimeOutEventName())
		{
			messageLog.Error(*FString::Printf(TEXT("@@ has a transition with an invalid label %s"), *name.ToString()), this);
		}
		else
		{
			checkDuplicates(name);
		}
	}

	// Make sure all deferred event names are valid
	for (auto const& name : deferredEvents)
	{
		if (!name.IsValid() || name.IsNone() || name == UGCFSMBasicState::GetTickEventName() || name == UGCFSMBasicState::GetTimeOutEventName())
		{
			messageLog.Error(*FString::Printf(TEXT("@@ has a deferred event with invalid label %s"), *name.ToString()), this);
		}
		else
		{
			checkDuplicates(name);
		}
	}

	// If we have an implementation class, we can check the context variable
	if (GetImplementationClass())
	{
		auto checkResult = CheckContext();
		switch (checkResult.result)
		{
		case ContextCheckResult::Compatible:
			// hurray!
			break;

		case ContextCheckResult::Incompatible:
			messageLog.Error(TEXT("@@ state class @@ has a Context variable of an incompatible type @@"), this, checkResult.implementationClass, checkResult.implementationContextClass);
			break;

		case ContextCheckResult::Error:
			if (checkResult.contextClass == nullptr)
			{
				messageLog.Warning(TEXT("@@ can't check type of Context variable in state class @@, since this class has no Context variable"), this, checkResult.implementationClass);
			}
			else // if (checkResult.implementationContextClass == nullptr)
			{
				messageLog.Note(TEXT("@@ state class @@ has no Context variable"), this, checkResult.implementationClass);
			}
		}
	}

}

void UGCFSMStateNode::ExpandNode(FKismetCompilerContext& compilerContext, UEdGraph* sourceGraph)
{
 	Super::ExpandNode(compilerContext, sourceGraph);

	if (auto fsmPin = GetFSMPin(compilerContext))
	{
		// Create function node to spawn state object
		auto spawnNode = compilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, sourceGraph);

		spawnNode->SetFromFunction(
			IsLocalState() ? UGCFSMLocalState::StaticClass()->FindFunctionByName("MakeLocalStateObject") :
			IsSubmachineState() ? UGCFSMSubmachineState::StaticClass()->FindFunctionByName("MakeSubmachineStateObject") :
			HasImplementationClass() ? UGCFSMState::StaticClass()->FindFunctionByName("MakeStateObject") :
			UGCFSMBasicState::StaticClass()->FindFunctionByName("MakeBasicStateObject")
		);

		spawnNode->AllocateDefaultPins();
		fsmPin->MakeLinkTo(spawnNode->FindPinChecked(TEXT("fsm")));
		spawnNode->FindPinChecked(TEXT("processTickEvent"))->DefaultValue = GetTickPin()->LinkedTo.Num() ? TEXT("1") : TEXT("0");
		spawnNode->FindPinChecked(TEXT("stateName"))->DefaultValue = NodeName.Len() > 0 ? NodeName : SuggestedNodeName();
		expandedExecPin = spawnNode->GetExecPin();
		compilerContext.MovePinLinksToIntermediate(*Pins[InExecPinIndex], *expandedExecPin);

		if (IsLocalState())
		{
			auto localGraph = localImplementationGraph.GetGraph();
			if (IsValid(localGraph))
			{
				spawnNode->FindPinChecked(TEXT("localStatePrefix"))->DefaultValue = localGraph->GetName();
			}
			else
			{
				compilerContext.MessageLog.Error(TEXT("Local state @@ must specify a valid event graph"), this);
			}
		}
		else if (IsSubmachineState())
		{
			auto submachineNode = GetSubmachineNode();
			compilerContext.MovePinLinksToIntermediate(*Pins[ReplicationOptionPinIndex], *spawnNode->FindPinChecked(TEXT("replicationOptions")));

			if (submachineNode == nullptr)
			{
				compilerContext.MessageLog.Error(TEXT("Submachine state @@ must specify a valid FSM"), this);
			}
			else if (startNode.IsSet() && submachineNode->CustomFunctionName == startNode.GetValue()->CustomFunctionName)
			{
				compilerContext.MessageLog.Error(TEXT("Submachine state @@ can't specify its own FSM"), this);
			}
			else
			{
				spawnNode->FindPinChecked(TEXT("submachineName"))->DefaultValue = submachineNode->GetFriendlyName();
			}
		}
		else if (HasImplementationClass())
		{
			compilerContext.MovePinLinksToIntermediate(*Pins[ImplementationPinIndex], *spawnNode->FindPinChecked(TEXT("implementationClass")));
		}

		// Add pins for state arguments
		auto execPin = spawnNode->GetThenPin();
		if (auto implementationClass = GetImplementationClass())
		{
			execPin = FKismetCompilerUtilities::GenerateAssignmentNodes(compilerContext, sourceGraph, spawnNode, this, spawnNode->GetReturnValuePin(), implementationClass);
		}

		// Create function node to actually enter the state
		auto enterStateNode = compilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, sourceGraph);
		enterStateNode->SetFromFunction(UGCFSM::StaticClass()->FindFunctionByName(TEXT("EnterState")));
		enterStateNode->AllocateDefaultPins();
		execPin->MakeLinkTo(enterStateNode->GetExecPin());
		fsmPin->MakeLinkTo(enterStateNode->FindPinChecked(UEdGraphSchema_K2::PN_Self));
		spawnNode->GetReturnValuePin()->MakeLinkTo(enterStateNode->FindPinChecked(TEXT("state")));
		enterStateNode->FindPinChecked(TEXT("nodeGuid"))->DefaultValue = NodeGuid.ToString();

		// Create a list of the transition pins that have outward connections
		TArray<UEdGraphPin*> validTransitionPins;
		for (int i = 0; i < transitionEvents.Num(); ++i)
		{
			auto pin = Pins[TransitionsPinStartIndex + i];
			if (pin->LinkedTo.Num() == 0)
			{
				compilerContext.MessageLog.Warning(TEXT("The transition pin @@ of @@ is not connected, the transition event will be ignored"), pin, this);
			}
			else
			{
				validTransitionPins.Add(pin);
			}
		}

		// Create a literal array containing all event names
		auto arrayNode = compilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(this, sourceGraph);
		arrayNode->NumInputs = validTransitionPins.Num() + deferredEvents.Num();
		arrayNode->AllocateDefaultPins();
		auto arrayPin = arrayNode->Pins.GetData();
		for (auto pin : validTransitionPins)
		{
			(*++arrayPin)->DefaultValue = pin->GetName();
		}
		for (auto& name : deferredEvents)
		{
			(*++arrayPin)->DefaultValue = name.ToString();
		}

		auto arrayOutputPin = arrayNode->GetOutputPin();
		arrayOutputPin->MakeLinkTo(enterStateNode->FindPinChecked(TEXT("processedEvents")));
		arrayNode->PinConnectionListChanged(arrayOutputPin); // this is necessary to make UK2Node_MakeArray coerce the type of the values
		enterStateNode->FindPinChecked(TEXT("numTransitions"))->DefaultValue = FString::Printf(TEXT("%d"), validTransitionPins.Num());

		// Count the output exec pins
		int outputExecPins = validTransitionPins.Num();

		// Check if the TimeOutEvent pin is connected
		auto timeOutEventPin = GetTimeOutEventPin();
		if (timeOutEventPin->LinkedTo.Num() == 0)
		{
			// the TimeOutEvent pin is not connected to anything, forget about it
			// don't even connect the max age pin, it's unnecessary
			timeOutEventPin = nullptr;
		}
		else
		{
			// connect the max age pin
			compilerContext.MovePinLinksToIntermediate(*GetTimeOutPin(), *spawnNode->FindPinChecked(TEXT("timeOut")));
			++outputExecPins;
		}

		// Check if the Tick pin is connected
		auto tickPin = GetTickPin();
		if (tickPin->LinkedTo.Num() == 0)
		{
			// the Tick is not connected to anything, forget about it
			// don't even connect the deltaTime pin, it's unnecessary
			tickPin = nullptr;
		}
		else
		{
			// connect the deltaTime pin
			compilerContext.MovePinLinksToIntermediate(*GetDeltaTimePin(), *enterStateNode->FindPinChecked(TEXT("deltaTime")));
			++outputExecPins;
		}

		// finally, connect the exec output pins
		if (outputExecPins == 0)
		{
			// no exec pin to connect
		}
		else
		{
			// create a Switch node to select among the different pins
			auto switchNode = compilerContext.SpawnIntermediateNode<UK2Node_SwitchName>(this, sourceGraph);

			// add special name for the tick pin, if present. Since it will be invoked more often, it's best to put it first
			if (tickPin)
			{
				switchNode->PinNames.Add(UGCFSMBasicState::GetTickEventName());
			}

			// add names for the valid transition pins
			for (auto pin : validTransitionPins)
			{
				switchNode->PinNames.Add(GetPinFName(pin));
			}

			// add special name for the timed event, if present
			if (timeOutEventPin)
			{
				switchNode->PinNames.Add(UGCFSMBasicState::GetTimeOutEventName());
			}

			// add a final pin to handle network replication
			switchNode->PinNames.Add(UGCFSMBasicState::GetReplicatedExitName());

			switchNode->bHasDefaultPin = false;
			switchNode->AllocateDefaultPins();
			enterStateNode->GetThenPin()->MakeLinkTo(switchNode->GetExecPin());
			enterStateNode->FindPinChecked(TEXT("eventName"))->MakeLinkTo(switchNode->GetSelectionPin());

			// a switch node has 3 pins before the output exec pins
			auto switchPinPtr = switchNode->Pins.GetData() + 3;

			// connect the special pin for the tick pin, if present
			if (tickPin)
			{
				check(IsTickPin(*switchPinPtr));
				compilerContext.MovePinLinksToIntermediate(*tickPin, **switchPinPtr);
				++switchPinPtr;
			}

			// connect the transitions pins
			auto transitionPinPtr = validTransitionPins.GetData();
			for (int i = 0; i < validTransitionPins.Num(); ++i, ++transitionPinPtr, ++switchPinPtr)
			{
				check((*transitionPinPtr)->GetName() == (*switchPinPtr)->GetName());
				compilerContext.MovePinLinksToIntermediate(**transitionPinPtr, **switchPinPtr);
			}

			// connect the special pin for the timed event, if present
			if (timeOutEventPin)
			{
				check(IsTimeOutEventPin(*switchPinPtr));
				compilerContext.MovePinLinksToIntermediate(*timeOutEventPin, **switchPinPtr);
				++switchPinPtr;
			}

			// finally, connect the network replication pin,
			check(IsReplicatedExitPin(*switchPinPtr));
			compilerContext.MovePinLinksToIntermediate(*Pins[ReplicatedExitPinIndex], **switchPinPtr);
			replicatedExitPin = *switchPinPtr;
		}
	}
	BreakAllNodeLinks();
}

class UGCFSMStateNode::VisualWidget : public SGraphNodeK2Base
{
public:
	SLATE_BEGIN_ARGS(VisualWidget) {}
	SLATE_END_ARGS()

	TArray<TSharedPtr<FName>> comboNames;

	void Construct(const FArguments&, UK2Node* InNode)
	{
		GraphNode = InNode;
		UpdateGraphNode();
	}

	FReply OnMouseButtonDoubleClick(const FGeometry& InMyGeometry, const FPointerEvent& InMouseEvent) override
	{
		if (InMouseEvent.IsMouseButtonDown(EKeys::LeftMouseButton))
		{
			CastChecked<UGCFSMStateNode>(GraphNode)->PrepareJumpTarget();
		}
		return SGraphNodeK2Base::OnMouseButtonDoubleClick(InMyGeometry, InMouseEvent);
	}

	static UGCFSMState* GetStateFromObject(UObject* object)
	{
		if (auto fsmState = Cast<UGCFSMState>(object))
		{
			return fsmState;
		}
		else if (object)
		{
			return UGCFSMUtilities::GetRootStateFromContext(object, false);
		}
		else
		{
			return nullptr;
		}
	}

	void GetNodeInfoPopups(FNodeInfoContext* Context, TArray<FGraphInformationPopupInfo>& Popups) const override
	{
		SGraphNodeK2Base::GetNodeInfoPopups(Context, Popups);
		FKismetNodeInfoContext* K2Context = (FKismetNodeInfoContext*)Context;
		if (UGCFSMState* fsmState = GetStateFromObject(K2Context->ActiveObjectBeingDebugged))
		{
			if (UGCFSM* fsm = fsmState->GetActiveFSMForGraphNode(GraphNode->NodeGuid))
			{
				const FLinearColor red { 0.9f, 0.0f, 0.0f };
				const FLinearColor orange { 0.9f, 0.5f, 0.0f };
				const FLinearColor green { 0.25f, 0.9f, 0.25f };

				new (Popups) FGraphInformationPopupInfo(NULL, red, FString::Printf(TEXT("Active since %.2fs "), fsm->GetActiveStateTime()));

				if (fsm->GetEventsBeingDeferred().Num() > 0)
				{
					float now = fsmState->GetRootTime();
					FString message { TEXT("Events being deferred: ") };
					for (auto event : fsm->GetEventsBeingDeferred())
					{
						float age = now - event.timeStamp;
						if (event.expiryTimeStamp == FLT_MAX)
						{
							message += FString::Printf(TEXT("\n    - %s (age %.2fs)"), *event.name.ToString(), age);
						}
						else if (now > event.expiryTimeStamp)
						{
							//message += FString::Printf(TEXT("\n    - %s (expired)"), *event.name.ToString(), age);
						}
						else
						{
							float maxAge = event.expiryTimeStamp - event.timeStamp;
							message += FString::Printf(TEXT("\n    - %s (age %.2fs/%.2fs)"), *event.name.ToString(), age, maxAge);
						}
					}

					new (Popups) FGraphInformationPopupInfo(NULL, orange, message);
				}

				FString debugInfo { fsm->GetDebugInfo() };
				if (!debugInfo.IsEmpty())
				{
					new (Popups) FGraphInformationPopupInfo(NULL, green, debugInfo);
				}
			}
		}
	}

	void CreatePinWidgets() override
	{
		SGraphNodeK2Base::CreatePinWidgets();

		UGCFSMStateNode* stateNode = CastChecked<UGCFSMStateNode>(GraphNode);

		if (stateNode->IsLocalState())
		{
			int selectedName = 0;
			comboNames.Empty(2);

			// fill list of graph names
			comboNames.Add(MakeShared<FName>("<Double-click to create new graph>"));

			auto currentGraph = stateNode->localImplementationGraph.GetGraph();
			if (UBlueprint* blueprint = stateNode->GetBlueprint())
			{
				for (auto graph : blueprint->UbergraphPages)
				{
					if (graph->bAllowDeletion)
					{
						if (currentGraph == graph)
						{
							selectedName = comboNames.Num();
						}
						comboNames.Add(MakeShared<FName>(graph->GetFName()));
					}
				}
			}

			LeftNodeBox->AddSlot()
				.AutoHeight()
				.Padding(FMargin { 32, 4, 4, 4 })
				[
					SNew(STextBlock)
					.Text(LOCTEXT("Label.ImplementationGraph", "Implementation Graph"))
					.TextStyle(FAppStyle::Get(), "Graph.Node.PinName")
					.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
				];

			LeftNodeBox->AddSlot()
				.AutoHeight()
				.Padding(FMargin { 36, 4, 4, 4 })
			[
				SNew(SNameComboBox)
				.ContentPadding(FMargin { 6.0f, 2.0f })
				.OptionsSource(&comboNames)
				.InitiallySelectedItem(comboNames[selectedName])
				.OnSelectionChanged(this, &VisualWidget::LocalGraphSelectionChanged)
				.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
			];
		}

		if (stateNode->IsSubmachineState())
		{
			int selectedName = 0;
			comboNames.Empty(2);

			// fill list of FSM names
			comboNames.Add(MakeShared<FName>("<Double-click to create new FSM>"));

			auto selectedNode = stateNode->GetSubmachineNode();
			TArray<UGCFSMStartNode*> startNodes;
			FBlueprintEditorUtils::GetAllNodesOfClass<UGCFSMStartNode>(stateNode->GetBlueprint(), startNodes);
			for (auto startNode : startNodes)
			{
				if (startNode == selectedNode)
				{
					selectedName = comboNames.Num();
				}
				comboNames.Add(MakeShared<FName>(*startNode->GetFriendlyName()));
			}

			LeftNodeBox->InsertSlot(1)
				.AutoHeight()
				.Padding(FMargin { 32, 4, 4, 4 })
				[
					SNew(STextBlock)
					.Text(LOCTEXT("Label.SubmachineName", "Submachine Name"))
					.TextStyle(FAppStyle::Get(), "Graph.Node.PinName")
					.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
				];

			LeftNodeBox->InsertSlot(2)
				.AutoHeight()
				.Padding(FMargin { 36, 4, 4, 4 })
				[
					SNew(SNameComboBox)
					.ContentPadding(FMargin { 6.0f, 2.0f })
					.OptionsSource(&comboNames)
					.InitiallySelectedItem(comboNames[selectedName])
					.OnSelectionChanged(this, &VisualWidget::SubmachineNameChanged)
					.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
				];
		}

		int insertPoint = stateNode->transitionEvents.Num();
		bool needSeparator = stateNode->transitionEvents.Num() > 0;

		auto addSeparator = [&]()
		{
			if (needSeparator)
			{
				RightNodeBox->InsertSlot(insertPoint++)
					.AutoHeight()
					.HAlign(HAlign_Right)
					.VAlign(VAlign_Center)
					.Padding(FMargin(1, 0, 1, 4))
					[
						SNew(SImage)
						.Image(FAppStyle::GetBrush("Graph.pin.DefaultPinSeparator"))
					];
			}
		};

		if (!stateNode->GetTimeOutEventPin()->bHidden)
		{
			addSeparator();
			insertPoint += 1;
			needSeparator = true;
		}

		if (stateNode->deferredEvents.Num())
		{
			addSeparator();

			for (auto const& name : stateNode->deferredEvents)
			{
				RightNodeBox->InsertSlot(insertPoint++)
					.AutoHeight()
					.HAlign(HAlign_Right)
					.VAlign(VAlign_Fill)
					.Padding(FMargin(10, 4, 20, 4))
					[
						SNew(STextBlock)
						.Text(FText::FromName(name))
						.TextStyle(FAppStyle::Get(), "Graph.Node.DefaultPinName")
						.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
					];
			}

			needSeparator = true;
		}

		if (stateNode->showTickFunction)
		{
			addSeparator();
		}
	}

	void LocalGraphSelectionChanged(TSharedPtr<FName> item, ESelectInfo::Type)
	{
		UGCFSMStateNode* stateNode = CastChecked<UGCFSMStateNode>(GraphNode);
		FScopedTransaction _ { LOCTEXT("SetLocalImplementation", "Set Implementation Graph") };
		stateNode->Modify();

		const FName itemName = *item;
		auto selectedGraph = stateNode->GetBlueprint()->UbergraphPages.FindByPredicate(
			[&itemName](UEdGraph* graph) { return graph->GetFName() == itemName; });
		stateNode->localImplementationGraph.SetGraph(selectedGraph ? *selectedGraph : nullptr);

		if (auto schema = stateNode->GetSchema())
		{
			schema->ForceVisualizationCacheClear();
		}
	}

	void SubmachineNameChanged(TSharedPtr<FName> item, ESelectInfo::Type)
	{
		UGCFSMStateNode* stateNode = CastChecked<UGCFSMStateNode>(GraphNode);
		FScopedTransaction _ { LOCTEXT("SetSubmachine", "Set Submachine FSM") };
		stateNode->Modify();

		TArray<UGCFSMStartNode*> nodes;
		FBlueprintEditorUtils::GetAllNodesOfClass(stateNode->GetBlueprint(), nodes);
		const FString itemName = item->ToString();
		auto selectedNode = nodes.FindByPredicate(
			[&itemName](UGCFSMStartNode* node) { return node->GetFriendlyName() == itemName; });
		stateNode->submachineNodeGuid = selectedNode ? (*selectedNode)->NodeGuid : FGuid {};

		if (auto schema = stateNode->GetSchema())
		{
			schema->ForceVisualizationCacheClear();
		}
	}
};

TSharedPtr<SGraphNode> UGCFSMStateNode::CreateVisualWidget()
{
	return SNew(VisualWidget, this);
}

#if ENGINE_MAJOR_VERSION ==	4 && ENGINE_MINOR_VERSION < 24
void UGCFSMStateNode::GetContextMenuActions(const FGraphNodeContextMenuBuilder& Context) const
{
	Super::GetContextMenuActions(Context);

	if (Context.Pin && Context.Pin->Direction == EGPD_Output && Context.Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec && !IsTickPin(Context.Pin) && !IsTimeOutEventPin(Context.Pin))
	{
		int index = Pins.IndexOfByKey(Context.Pin) - TransitionsPinStartIndex;
		check(transitionEvents.IsValidIndex(index));

		Context.MenuBuilder->BeginSection("GCFSM", LOCTEXT("CtxMenu.Event.Title", "FSM Event Pin"));
		Context.MenuBuilder->AddMenuEntry(
			LOCTEXT("CtxMenu.AddEvent", "Add new transition event"),
			{},
			{},
			FUIAction(FExecuteAction::CreateUObject(const_cast<UGCFSMStateNode*>(this), &UGCFSMStateNode::AddTransitionEvent, index)));

		Context.MenuBuilder->AddMenuEntry(
			LOCTEXT("CtxMenu.RemoveEvent", "Remove this transition event"),
			{},
			{},
			FUIAction(FExecuteAction::CreateUObject(const_cast<UGCFSMStateNode*>(this), &UGCFSMStateNode::RemoveTransitionEvent, index)));
		Context.MenuBuilder->EndSection();
	}
	else
	{
		Context.MenuBuilder->BeginSection("GCFSM", LOCTEXT("CtxMenu.State.Title", "FSM State"));
		if (Context.Pin == nullptr)
		{
			if (nodeKind != EGCFSMStateNodeKind::Regular)
			{
				Context.MenuBuilder->AddMenuEntry(
					LOCTEXT("CtxMenu.ConvertToRegular", "Convert to Regular State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Regular)));
			}

			if (nodeKind != EGCFSMStateNodeKind::Local)
			{
				Context.MenuBuilder->AddMenuEntry(
					LOCTEXT("CtxMenu.ConvertToLocal", "Convert to Local State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Local)));
			}

			if (nodeKind != EGCFSMStateNodeKind::Submachine)
			{
				Context.MenuBuilder->AddMenuEntry(
					LOCTEXT("CtxMenu.ConvertToSubmachine", "Convert to Submachine State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Submachine)));
			}
		}

		if (IsRegularState() && (Context.Pin == nullptr || Context.Pin == Pins[ImplementationPinIndex]))
		{
			auto checkResult = CheckContext();
			if (checkResult.implementationClass)
			{
				if (checkResult.contextClass && checkResult.implementationClass->ClassGeneratedBy)
				{
					if (checkResult.implementationContextClass && checkResult.result == ContextCheckResult::Incompatible)
					{
						Context.MenuBuilder->AddMenuEntry(
							LOCTEXT("CtxMenu.FixContext", "Fix Context Variable"),
							LOCTEXT("CtxMenu.FixContext.Tooltip", "Fix the type of the Context variable in the state class"),
							{},
							FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::AddContextVariable, checkResult.contextClass, true)));
					}
					else if (checkResult.implementationContextClass == nullptr)
					{
						Context.MenuBuilder->AddMenuEntry(
							LOCTEXT("CtxMenu.AddContext", "Add Context Variable"),
							LOCTEXT("CtxMenu.AddContext.ToolTip", "Add a Context variable of the correct type to the state class"),
							{},
							FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::AddContextVariable, checkResult.contextClass, false)));
					}
				}
			}
			else if (Pins[ImplementationPinIndex]->LinkedTo.Num() == 0)
			{
				Context.MenuBuilder->AddMenuEntry(
					LOCTEXT("CtxMenu.CreateClass", "Create New State Class"),
					LOCTEXT("CtxMenu.CreateClass.Tooltip", "Create a new blueprint for a state class"),
					{},
					FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::CreateNewImplementation, checkResult.contextClass)));
			}
		}
		Context.MenuBuilder->EndSection();
	}
}
#else
void UGCFSMStateNode::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);

	auto pin = Context->Pin;
	auto pThis = const_cast<UGCFSMStateNode*>(this);
	if (pin && pin->Direction == EGPD_Output && pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec && !IsTickPin(pin) && !IsTimeOutEventPin(pin))
	{
		int index = Pins.IndexOfByKey(pin) - TransitionsPinStartIndex;
		check(transitionEvents.IsValidIndex(index));

		FToolMenuSection& Section = Menu->AddSection("GCFSM_EventPin", LOCTEXT("CtxMenu.Event.Title", "FSM Event Pin"));
		Section.AddMenuEntry(
			"AddEvent",
			LOCTEXT("CtxMenu.AddEvent", "Add new transition event"),
			{},
			{},
			FUIAction(FExecuteAction::CreateUObject(pThis, &UGCFSMStateNode::AddTransitionEvent, index)));

		Section.AddMenuEntry(
			"RemoveEvent",
			LOCTEXT("CtxMenu.RemoveEvent", "Remove this transition event"),
			{},
			{},
			FUIAction(FExecuteAction::CreateUObject(pThis, &UGCFSMStateNode::RemoveTransitionEvent, index)));
	}
	else
	{
		FToolMenuSection& Section = Menu->AddSection("GCFSM_State", LOCTEXT("CtxMenu.State.Title", "FSM State"));
		if (pin == nullptr)
		{
			if (nodeKind != EGCFSMStateNodeKind::Regular)
			{
				Section.AddMenuEntry(
					"ConvertToRegular",
					LOCTEXT("CtxMenu.ConvertToRegular", "Convert to Regular State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(pThis, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Regular)));
			}

			if (nodeKind != EGCFSMStateNodeKind::Local)
			{
				Section.AddMenuEntry(
					"ConvertToLocal",
					LOCTEXT("CtxMenu.ConvertToLocal", "Convert to Local State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(pThis, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Local)));
			}

			if (nodeKind != EGCFSMStateNodeKind::Submachine)
			{
				Section.AddMenuEntry(
					"ConvertToSubmachine",
					LOCTEXT("CtxMenu.ConvertToSubmachine", "Convert to Submachine State"),
					{},
					{},
					FUIAction(FExecuteAction::CreateUObject(pThis, &UGCFSMStateNode::SetNodeKind, EGCFSMStateNodeKind::Submachine)));
			}
		}

		if (IsRegularState() && (pin == nullptr || pin == Pins[ImplementationPinIndex]))
		{
			auto checkResult = CheckContext();
			if (checkResult.implementationClass)
			{
				if (checkResult.contextClass && checkResult.implementationClass->ClassGeneratedBy)
				{
					if (checkResult.implementationContextClass && checkResult.result == ContextCheckResult::Incompatible)
					{
						Section.AddMenuEntry(
							"FixContextVariable",
							LOCTEXT("CtxMenu.FixContext", "Fix Context Variable"),
							LOCTEXT("CtxMenu.FixContext.Tooltip", "Fix the type of the Context variable in the state class"),
							{},
							FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::AddContextVariable, checkResult.contextClass, true)));
					}
					else if (checkResult.implementationContextClass == nullptr)
					{
						Section.AddMenuEntry(
							"AddContextVariable",
							LOCTEXT("CtxMenu.AddContext", "Add Context Variable"),
							LOCTEXT("CtxMenu.AddContext.ToolTip", "Add a Context variable of the correct type to the state class"),
							{},
							FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::AddContextVariable, checkResult.contextClass, false)));
					}
				}
			}
			else if (Pins[ImplementationPinIndex]->LinkedTo.Num() == 0)
			{
				Section.AddMenuEntry(
					"CreateStateClass",
					LOCTEXT("CtxMenu.CreateClass", "Create New State Class"),
					LOCTEXT("CtxMenu.CreateClass.Tooltip", "Create a new blueprint for a state class"),
					{},
					FUIAction(FExecuteAction::CreateUObject(this, &UGCFSMStateNode::CreateNewImplementation, checkResult.contextClass)));
			}
		}
	}
}
#endif

void UGCFSMStateNode::SetNodeKind(EGCFSMStateNodeKind newKind)
{
	nodeKind = newKind;
	Pins[ImplementationPinIndex]->BreakAllPinLinks();
	Pins[ImplementationPinIndex]->ResetDefaultValue();
	ReconstructNode();
}

void UGCFSMStateNode::AddTransitionEvent(int eventIndex)
{
	transitionEvents.Insert(NAME_None, eventIndex);
	ReconstructNode();
}

void UGCFSMStateNode::RemoveTransitionEvent(int eventIndex)
{
	transitionEvents.RemoveAt(eventIndex);
	ReconstructNode();
}

void UGCFSMStateNode::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& oldPins)
{
	AllocateDefaultPins();
	CreatePinsForClass(oldPins[ImplementationPinIndex]->LinkedTo.Num() == 0 ? Cast<UClass>(oldPins[ImplementationPinIndex]->DefaultObject) : nullptr);
	RestoreSplitPins(oldPins);
}

void UGCFSMStateNode::CreatePinsForClass(UClass* implementationClass, TArray<UEdGraphPin*>* classPins)
{
	// based on UK2Node_ConstructObjectFromClass::CreatePinsForClass

	if (implementationClass)
	{
		auto schema = GetDefault<UEdGraphSchema_K2>();
		auto classDefaultObject = implementationClass->GetDefaultObject(false);
		for (TFieldIterator<FProperty> propertyIt(implementationClass, EFieldIteratorFlags::IncludeSuper); propertyIt; ++propertyIt)
		{
			auto property = *propertyIt;
			const bool bIsDelegate = property->IsA(FMulticastDelegateProperty::StaticClass());
			const bool bIsExposedToSpawn = UEdGraphSchema_K2::IsPropertyExposedOnSpawn(property);
			const bool bIsSettableExternally = !property->HasAnyPropertyFlags(CPF_DisableEditOnInstance);

			if (bIsExposedToSpawn &&
				!property->HasAnyPropertyFlags(CPF_Parm) &&
				bIsSettableExternally &&
				property->HasAllPropertyFlags(CPF_BlueprintVisible) &&
				!bIsDelegate &&
				(nullptr == FindPin(property->GetName())) &&
				FBlueprintEditorUtils::PropertyStillExists(property))
			{
				if (UEdGraphPin* pin = CreatePin(EGPD_Input, {}, {}, nullptr, property->GetFName()))
				{
					schema->ConvertPropertyToPinType(property, pin->PinType);
					if (classPins)
					{
						classPins->Add(pin);
					}

					if (classDefaultObject && schema->PinDefaultValueIsEditable(*pin))
					{
						FString defaultValueAsString;
						verify(FBlueprintEditorUtils::PropertyValueToString(property, reinterpret_cast<const uint8*>(classDefaultObject), defaultValueAsString));
						schema->SetPinAutogeneratedDefaultValue(pin, defaultValueAsString);
					}

					schema->ConstructBasicPinTooltip(*pin, property->GetToolTipText(), pin->PinToolTip);
				}
			}
		}
	}
}

void UGCFSMStateNode::PinDefaultValueChanged(UEdGraphPin* pin)
{
	SyncPropertyWithPin(pin);

	if (pin == Pins[ImplementationPinIndex] || pin == GetTimeOutPin())
	{
		ReconstructNode();
	}
}

void UGCFSMStateNode::PinConnectionListChanged(UEdGraphPin* pin)
{
	if (pin == Pins[ImplementationPinIndex] || pin == GetTimeOutPin())
	{
		bReconstructNode = true;
	}
}

void UGCFSMStateNode::NodeConnectionListChanged()
{
	Super::NodeConnectionListChanged();

	if (bReconstructNode)
	{
		ReconstructNode();

		UBlueprint* Blueprint = GetBlueprint();
		if (!Blueprint->bBeingCompiled)
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
			Blueprint->BroadcastChanged();
		}
	}
}

UObject* UGCFSMStateNode::GetJumpTargetForDoubleClick() const
{
	if (IsLocalState())
	{
		return GetValid(localImplementationGraph.GetGraph());
	}
	else if (IsSubmachineState())
	{
		return GetSubmachineNode();
	}
	else // if (IsRegularState())
	{
		auto checkResult = CheckContext();
		return checkResult.implementationClass ? checkResult.implementationClass->ClassGeneratedBy : nullptr;
	}
}

void UGCFSMStateNode::PrepareJumpTarget()
{
	if (IsLocalState())
	{
		auto graph = localImplementationGraph.GetGraph();
		if (!IsValid(graph))
		{
			CreateNewLocalImplementation();
		}
	}
	else if (IsSubmachineState())
	{
		auto node = GetSubmachineNode();
		if (node == nullptr)
		{
			CreateNewSubmachineImplementation();
		}
	}
	else // if (IsRegularState())
	{
		auto checkResult = CheckContext();
		if (checkResult.implementationClass == nullptr)
		{
			CreateNewImplementation(checkResult.contextClass ? checkResult.contextClass : UObject::StaticClass());
		}
	}
}

void UGCFSMStateNode::CreateNewLocalImplementation()
{
	auto blueprint = GetBlueprint();
	check(blueprint);

	const FScopedTransaction Transaction(LOCTEXT("AddNewLocalImplementation", "Add New Local State Graph"));
	blueprint->Modify();

	FName graphName = FBlueprintEditorUtils::FindUniqueKismetName(blueprint, TEXT("NewLocalState"));
	UEdGraph* newGraph = FBlueprintEditorUtils::CreateNewGraph(blueprint, graphName, UEdGraph::StaticClass(), GetSchema()->GetClass());
	if (newGraph)
	{
		FBlueprintEditorUtils::AddUbergraphPage(blueprint, newGraph);

		// Create the entry/exit/tick nodes
		auto createNode = [newGraph] (int y, ELocalStateEntryPoint kind) {
			FGraphNodeCreator<UGCFSMLocalStateEntryPointNode> nodeCreator { *newGraph };
			auto node = nodeCreator.CreateNode();
			node->NodePosX = 0;
			node->NodePosY = y;
			node->kind = kind;
			node->MakeAutomaticallyPlacedGhostNode();
			node->bCommentBubbleVisible = true;
			UEdGraphSchema::SetNodeMetaData(node, FNodeMetadata::DefaultGraphNode);
			nodeCreator.Finalize();
		};

		createNode(0, ELocalStateEntryPoint::OnEnter);
		createNode(256, ELocalStateEntryPoint::OnExit);
		createNode(512, ELocalStateEntryPoint::OnTick);

		// update localImplementationGraph to point to the newly created graph
		Modify();
		localImplementationGraph.SetGraph(newGraph);
	}
}

void UGCFSMStateNode::CreateNewSubmachineImplementation()
{
	auto blueprint = GetBlueprint();
	check(blueprint);

	const FScopedTransaction Transaction(LOCTEXT("AddNewSubmachineImplementation", "Add New Submachine FSM"));
	blueprint->Modify();

	// Create the entry/exit/tick nodes
	FGraphNodeCreator<UGCFSMStartNode> nodeCreator { *GetGraph() };
	auto node = nodeCreator.CreateUserInvokedNode(true);
	node->CustomFunctionName = FBlueprintEditorUtils::FindUniqueKismetName(blueprint, TEXT("NewSubmachine"));
	auto pos = GetGraph()->GetGoodPlaceForNewNode();
	node->NodePosX = pos.X;
	node->NodePosY = pos.Y;
	nodeCreator.Finalize();

	// update submachineNodeGuid to point to the newly created submachine
	Modify();
	submachineNodeGuid = node->NodeGuid;
}

void UGCFSMStateNode::CreateNewImplementation(UClass* contextClass) const
{
	auto bpClass = GetBlueprintClassFromNode();
	FString pathName = bpClass->GetPathName();
	int index;
	if (pathName.FindLastChar('/', index))
	{
		pathName = pathName.Left(index);
	}

	FAssetToolsModule& AssetToolsModule = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools");
	UObject* newObject = AssetToolsModule.Get().CreateAssetWithDialog(
		TEXT("NewStateClass"),
		pathName,
		UBlueprint::StaticClass(),
		NewObject<UGCFSMStateFactory>(),
		TEXT("UCreateNewImplementation"));

	if (auto newBlueprint = Cast<UBlueprint>(newObject))
	{
		FScopedTransaction _ { LOCTEXT("SetImplementationClass", "Set Implementation Class") };
		Pins[ImplementationPinIndex]->Modify();
		Pins[ImplementationPinIndex]->DefaultObject = newBlueprint->GeneratedClass;
		AddContextVariable(contextClass, false);
	}
}

UGCFSMStateNode::ContextCheckResult UGCFSMStateNode::CheckContext() const
{
	ContextCheckResult result {};
	result.contextClass = GCFSMEditorUtilities::GetContextClassForNode(this);
	result.implementationClass = Cast<UClass>(Pins[ImplementationPinIndex]->DefaultObject);
	if (result.implementationClass)
	{
		result.implementationContextClass = UGCFSMState::GetContextClassForClass(result.implementationClass);
	}

	if (result.implementationContextClass && result.contextClass)
	{
		result.result = result.contextClass->IsChildOf(result.implementationContextClass) ? ContextCheckResult::Compatible : ContextCheckResult::Incompatible;
	}
	else
	{
		result.result = ContextCheckResult::Error;
	}
	return result;
}

void UGCFSMStateNode::AddContextVariable(UClass* contextClass, bool modifyExisting) const
{
	auto implClass = Cast<UClass>(Pins[ImplementationPinIndex]->DefaultObject);
	auto implBlueprint = Cast<UBlueprint>(implClass->ClassGeneratedBy);
	FEdGraphPinType newVarType;
	newVarType.PinCategory = UEdGraphSchema_K2::PC_Object;
	newVarType.PinSubCategoryObject = contextClass;

	if (modifyExisting)
	{
		FBlueprintEditorUtils::ChangeMemberVariableType(implBlueprint, TEXT("Context"), newVarType);
		FKismetEditorUtilities::CompileBlueprint(implBlueprint, EBlueprintCompileOptions::None, nullptr);
	}
	else if (FBlueprintEditorUtils::AddMemberVariable(implBlueprint, TEXT("Context"), newVarType))
	{
		FKismetEditorUtilities::CompileBlueprint(implBlueprint, EBlueprintCompileOptions::None, nullptr);
	}
	else
	{
		FFormatNamedArguments Args;
		Args.Add(TEXT("ClassName"), FText::FromName(implClass->GetFName()));
		GEditor->OnModalMessageDialog(
#if ENGINE_MAJOR_VERSION ==	5 && ENGINE_MINOR_VERSION > 2
			EAppMsgCategory::Error,
#endif
			EAppMsgType::Ok,
			FText::Format(LOCTEXT("FailedToAdd.Msg", "Failed to add member variable to class {ClassName}"), Args),
			LOCTEXT("FailedToAdd.Title", "Add FSM member variable"));
	}
}

bool UGCFSMStateNode::HasExternalDependencies(TArray<class UStruct*>* optionalOutput) const
{
	auto implementationClass = GetImplementationClass();
	bool result = implementationClass && implementationClass->ClassGeneratedBy != GetBlueprint();
	if (result && optionalOutput)
	{
		optionalOutput->AddUnique(implementationClass);
	}
	return Super::HasExternalDependencies(optionalOutput) || result;
}

void UGCFSMStateNode::GetMenuActions(FBlueprintActionDatabaseRegistrar& actionRegistrar) const
{
	UClass* actionKey = GetClass();
	if (actionRegistrar.IsOpenForRegistration(actionKey))
	{
		// create three actions for the three variants of the state nodes: "regular", "local" and "submachine"
		// use the node delegate to load the default events (doing it in ctor may have unintended
		// consequences as it may affect already placed nodes)

		auto customize = [](UEdGraphNode* NewNode, bool bIsTemplateNode, EGCFSMStateNodeKind kind)
		{
			auto node = CastChecked<UGCFSMStateNode>(NewNode);
			node->nodeKind = kind;
			if (auto settings = GetMutableDefault<UGCFSMEditorSettings>())
			{
				node->transitionEvents = settings->defaultTransitionEvents;
			}
		};

		auto nodeSpawner = UBlueprintNodeSpawner::Create(actionKey);
		nodeSpawner->CustomizeNodeDelegate.BindLambda(customize, EGCFSMStateNodeKind::Regular);
		actionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);

		nodeSpawner = UBlueprintNodeSpawner::Create(actionKey);
		nodeSpawner->CustomizeNodeDelegate.BindLambda(customize, EGCFSMStateNodeKind::Local);
		actionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);

		nodeSpawner = UBlueprintNodeSpawner::Create(actionKey);
		nodeSpawner->CustomizeNodeDelegate.BindLambda(customize, EGCFSMStateNodeKind::Submachine);
		actionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);
	}
}

#undef LOCTEXT_NAMESPACE
