// Copyright (c) 2018 Gamecentric, All rights reserved

#include "GCFSMPolyNodeWithName.h"
#include "GCFSMEditorModule.h"
#include "GCFSMStartNode.h"
#include "EdGraphSchema_K2.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetCompiler.h"
#include "SGraphPinNameList.h"
#include "KismetNodes/SGraphNodeK2Base.h"

#define LOCTEXT_NAMESPACE "GCFSM.Nodes"

void UGCFSMPolyNodeWithName::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	auto schema = GetDefault<UEdGraphSchema_K2>();

	check(Pins.Num() == NamePinIndex);
	auto pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, {}, nullptr, "FSM");
	schema->SetPinAutogeneratedDefaultValueBasedOnType(pin);
}

void UGCFSMPolyNodeWithName::CheckGuid(bool tryDefault)
{
	auto nodes = GetValidFSMNodes();
	auto namePin = Pins[NamePinIndex];

	FGuid goodGuid;
	FString goodName = FName {}.ToString(); // goodName must be a valid string representation of an FName, so the default is "None"

	if (tryDefault && nodes.Num() == 1)
	{
		// We only have one valid FSM, just use it as a default
		goodGuid = nodes[0]->NodeGuid;
		goodName = nodes[0]->GetFriendlyName();
	}
	else if (fsmNodeGuid.IsValid())
	{
		// check if guid is still a valid FSM node guid, fix name accordingly
		for (auto node : nodes)
		{
			if (node->NodeGuid == fsmNodeGuid)
			{
				goodGuid = fsmNodeGuid;
				goodName = node->GetFriendlyName();
				break;
			}
		}
	}
	else if (namePin->DefaultValue.Len() > 0 && namePin->DefaultValue != goodName)
	{
		// compatibility code: we have a valid name but not a guid, it might happen while transitioning between GC FSM v1.5 and v1.6
		for (auto node : nodes)
		{
			if (node->GetFriendlyName() == namePin->DefaultValue)
			{
				goodGuid = node->NodeGuid;
				goodName = namePin->DefaultValue;
				break;
			}
		}
	}

	if (fsmNodeGuid != goodGuid)
	{
		Modify();
		fsmNodeGuid = goodGuid;
	}

	if (namePin->DefaultValue != goodName)
	{
		namePin->Modify();
		namePin->DefaultValue = goodName;
	}
}

void UGCFSMPolyNodeWithName::ReconstructNode()
{
	Super::ReconstructNode();
	CheckGuid(false);
}

void UGCFSMPolyNodeWithName::PostPlacedNewNode()
{
	CheckGuid(true);
	Super::PostPlacedNewNode();
}

void UGCFSMPolyNodeWithName::NodeConnectionListChanged()
{
	Super::NodeConnectionListChanged();
	CheckGuid(true);
	ReconstructNode();
}

TArray<UGCFSMStartNode*> UGCFSMPolyNodeWithName::GetValidFSMNodes()
{
	TArray<UGCFSMStartNode*> startNodes;
	UClass* bpClass = GetEffectiveTargetClass();
	if (UBlueprint* blueprint = Cast<UBlueprint>(bpClass->ClassGeneratedBy))
	{
		FBlueprintEditorUtils::GetAllNodesOfClass<UGCFSMStartNode>(blueprint, startNodes);
	}
	return startNodes;
}

void UGCFSMPolyNodeWithName::PinDefaultValueChanged(UEdGraphPin* pin)
{
	Super::PinDefaultValueChanged(pin);

	if (pin == Pins[NamePinIndex])
	{
		fsmNodeGuid.Invalidate();

		for (auto node : GetValidFSMNodes())
		{
			if (pin->DefaultValue == node->GetFriendlyName())
			{
				fsmNodeGuid = node->NodeGuid;
				break;
			}
		}
	}
}

bool UGCFSMPolyNodeWithName::HasExternalDependencies(TArray<UStruct*>* optionalOutput) const
{
	bool result = Super::HasExternalDependencies(optionalOutput);
	UClass* bpClass = GetEffectiveTargetClass();
	if (bpClass && bpClass != GetBlueprintClassFromNode())
	{
		if (optionalOutput)
		{
			optionalOutput->Add(bpClass);
		}
		result = true;
	}
	return result;
}

class UGCFSMPolyNodeWithName::VisualWidget : public SGraphNodeK2Base
{
public:
	SLATE_BEGIN_ARGS(VisualWidget) {}
	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs, UK2Node* InNode)
	{
		GraphNode = InNode;
		UpdateGraphNode();
	}

	TSharedPtr<SGraphPin> CreatePinWidget(UEdGraphPin* pin) const override
	{
		if (pin->PinName == TEXT("FSM"))
		{
			auto node = CastChecked<UGCFSMPolyNodeWithName>(GraphNode);
			auto fsmNodes = node->GetValidFSMNodes();
			if (fsmNodes.Num())
			{
				TArray<TSharedPtr<FName>> sharedNames;
				for (auto& fsmNode : fsmNodes)
				{
					auto nodeName = fsmNode->GetFriendlyName();
					if (fsmNode->NodeGuid == node->fsmNodeGuid && pin->DefaultValue != nodeName)
					{
						// force pin default value to actual node name, in case it has changed
						pin->Modify();
						pin->DefaultValue = nodeName;
					}
					sharedNames.Add(MakeShared<FName>(*nodeName));
				}
				return SNew(SGraphPinNameList, pin, sharedNames);
			}
		}
		return SGraphNodeK2Base::CreatePinWidget(pin);
	}
};

TSharedPtr<SGraphNode> UGCFSMPolyNodeWithName::CreateVisualWidget()
{
	return SNew(VisualWidget, this);
}

void UGCFSMPolyNodeWithName::ExpandNode(FKismetCompilerContext& compilerContext, UEdGraph* sourceGraph)
{
	Super::ExpandNode(compilerContext, sourceGraph);

	// Validate Name pin if possible
	UClass* targetClass = GetEffectiveTargetClass();
	if (Pins[NamePinIndex]->LinkedTo.Num() == 0)
	{
		if (FindEntryPointNodeByFriendlyName<UGCFSMStartNode>(targetClass, Pins[NamePinIndex]->DefaultValue) == nullptr)
		{
			compilerContext.MessageLog.Error(*LOCTEXT("FunctionNotFound", "@@ invalid FSM for target class @@").ToString(), this, targetClass);
		}
	}
}

#undef LOCTEXT_NAMESPACE
