// Copyright (c) 2018 Gamecentric, All rights reserved

#include "GCFSMTriggerEventNode.h"
#include "GCFSMEditorModule.h"
#include "GCFSMUtilities.h"
#include "GCFSMState.h"
#include "EdGraphSchema_K2.h"
#include "KismetCompiler.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetNodes/SGraphNodeK2Base.h"
#include "KismetNodes/KismetNodeInfoContext.h"
#include "EnumHelpers.h"
#include "ScopedTransaction.h"
#include <array>

ENUM_HELPERS_NAME(EGCFSMTriggerEventTargetPolicy, GCFSM);
ENUM_HELPERS_NAME(EGCFSMTriggerEventQueuePolicy, GCFSM);

#define LOCTEXT_NAMESPACE "GCFSM.TriggerEventNode"

UGCFSMTriggerEventNode::UGCFSMTriggerEventNode()
{
	propagateToSubstates = true;
	triggerInternalEvents = true;
}

bool UGCFSMTriggerEventNode::ShouldHideTargetPolicy() const
{
	return GetEffectiveTargetClass()->IsChildOf<UGCFSMState>() == false;
}

bool UGCFSMTriggerEventNode::IsPinPropertyAvailable(const PinProperty& pinProperty) const
{
	return pinProperty.pinName != TEXT("TargetPolicy") || !ShouldHideTargetPolicy();
}

void UGCFSMTriggerEventNode::AllocateDefaultPins()
{
	auto schema = GetDefault<UEdGraphSchema_K2>();

	Super::AllocateDefaultPins();

	UEdGraphPin* pin;

	check(Pins.Num() == NamePinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, {}, nullptr, "Event");
	pin->PinToolTip = LOCTEXT("NamePin.Tooltip", "The event to trigger").ToString();
	schema->SetPinAutogeneratedDefaultValueBasedOnType(pin);

	check(Pins.Num() == TargetPolicyPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, {}, EnumHelpers::GetUEnum<EGCFSMTriggerEventTargetPolicy>(), "TargetPolicy");
	pin->PinFriendlyName = LOCTEXT("TargetPolicyPin", "Effective Target");
	pin->PinToolTip = LOCTEXT("TargetPolicyPin.Tooltip", "Specifies whether the event is effectively sent to the target object or to its Context object").ToString();

	check(Pins.Num() == PropagatePolicyPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, {}, nullptr, "PropagateToSubstates");
	pin->PinFriendlyName = LOCTEXT("PropagatePolicyPin", "Trigger in Substates");
	pin->PinToolTip = LOCTEXT("PropagatePolicyPin.Tooltip", "Specifies whether or not the event is also triggered in the active states of the running FSMs").ToString();

	check(Pins.Num() == TriggerInternalPolicyPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, {}, nullptr, "TriggerInternalEvents");
	pin->PinToolTip = LOCTEXT("TargetPolicyPin.Tooltip", "Specifies whether or not internal events are processed").ToString();

	check(Pins.Num() == QueuePolicyPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, {}, EnumHelpers::GetUEnum<EGCFSMTriggerEventQueuePolicy>(), "QueuePolicy");
	pin->PinToolTip = LOCTEXT("TargetPolicyPin.Tooltip", "Specifies the queue policy").ToString();

	check(Pins.Num() == ExpireAfterPinIndex);
	pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, nullptr, "ExpireAfter");
	pin->PinToolTip = LOCTEXT("TargetPolicyPin.Tooltip", "Specifies a time in seconds after which this event is to be discarded").ToString();

	bReconstructNode = false;
}

void UGCFSMTriggerEventNode::PostPlacedNewNode()
{
	Super::PostPlacedNewNode();
	SyncAllPins();
}

void UGCFSMTriggerEventNode::PostReconstructNode()
{
	bReconstructNode = false;
	SyncAllPins();
	Super::PostReconstructNode();
}

void UGCFSMTriggerEventNode::PinDefaultValueChanged(UEdGraphPin* pin)
{
	Super::PinDefaultValueChanged(pin);
	SyncPropertyWithPin(pin);
}

void UGCFSMTriggerEventNode::NotifyPinConnectionListChanged(UEdGraphPin* pin)
{
	Super::NotifyPinConnectionListChanged(pin);

	if (pin == Pins[TargetPinIndex])
	{
		auto targetPolicyPin = Pins[TargetPolicyPinIndex];
		bool hidden = ShouldHideTargetPolicy();
		if (targetPolicyPin->bHidden != hidden)
		{
			if (auto schema = GetSchema())
			{
				schema->BreakPinLinks(*targetPolicyPin, true);
				schema->ResetPinToAutogeneratedDefaultValue(targetPolicyPin);
			}
			bReconstructNode = true;
		}
	}
}

void UGCFSMTriggerEventNode::NodeConnectionListChanged()
{
	Super::NodeConnectionListChanged();

	if (bReconstructNode)
	{
		ReconstructNode();

		UBlueprint* Blueprint = GetBlueprint();
		if (!Blueprint->bBeingCompiled)
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
			Blueprint->BroadcastChanged();
		}
	}
}

void UGCFSMTriggerEventNode::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	Super::PostEditChangeProperty(propertyChangedEvent);
	
	if (propertyChangedEvent.Property)
	{
		SyncPinWithProperty(propertyChangedEvent.Property);

		if (const UEdGraphSchema* Schema = GetSchema())
		{
			Schema->ForceVisualizationCacheClear();
		}
	}
}

FSlateIcon UGCFSMTriggerEventNode::GetIconAndTint(FLinearColor& outColor) const
{
	return FSlateIcon("GCFSM", "NodeIcon.TriggerEvent");
}

FText UGCFSMTriggerEventNode::GetNodeTitle(ENodeTitleType::Type titleType) const
{
	if (titleType != ENodeTitleType::FullTitle)
	{
		return LOCTEXT("NodeTitle", "Trigger FSM Event");
	}
	else
	{
		FFormatNamedArguments Args;
		Args.Add(TEXT("Target"), GetEffectiveTargetClass()->GetDisplayNameText());
		return FText::Format(LOCTEXT("FullTitle", "Trigger FSM Event\nTarget is {Target}"), Args);
	}

}

FText UGCFSMTriggerEventNode::GetTooltipText() const
{
	return LOCTEXT("ToolTip", "Triggers an event in the specified FSMs of the target Context or target state object");
}

void UGCFSMTriggerEventNode::ExpandNode(FKismetCompilerContext& compilerContext, UEdGraph* sourceGraph)
{
	Super::ExpandNode(compilerContext, sourceGraph);

	auto callFunction = compilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, sourceGraph);
	callFunction->SetFromFunction(UGCFSMUtilities::StaticClass()->FindFunctionByName(TEXT("TriggerEvent")));
	callFunction->AllocateDefaultPins();
	compilerContext.MovePinLinksToIntermediate(*Pins[InExecPinIndex], *callFunction->GetExecPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[OutExecPinIndex], *callFunction->GetThenPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[TargetPinIndex], *callFunction->FindPinChecked(TEXT("stateOrContext")));
	compilerContext.MovePinLinksToIntermediate(*Pins[NamePinIndex], *callFunction->FindPinChecked(TEXT("eventName")));
	auto& targetPolicyPin = *Pins[TargetPolicyPinIndex];
	if (!targetPolicyPin.bHidden)
	{
		compilerContext.MovePinLinksToIntermediate(targetPolicyPin, *callFunction->FindPinChecked(TEXT("targetPolicy")));
	}
	compilerContext.MovePinLinksToIntermediate(*Pins[PropagatePolicyPinIndex], *callFunction->FindPinChecked(TEXT("propagateToSubstates")));
	compilerContext.MovePinLinksToIntermediate(*Pins[TriggerInternalPolicyPinIndex], *callFunction->FindPinChecked(TEXT("triggerInternalEvents")));
	compilerContext.MovePinLinksToIntermediate(*Pins[QueuePolicyPinIndex], *callFunction->FindPinChecked(TEXT("queuePolicy")));
	compilerContext.MovePinLinksToIntermediate(*Pins[ExpireAfterPinIndex], *callFunction->FindPinChecked(TEXT("expireAfter")));
	BreakAllNodeLinks();
}

class UGCFSMTriggerEventNode::VisualWidget : public SGraphNodeK2Base
{
public:
	SLATE_BEGIN_ARGS(VisualWidget) {}
	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs, UK2Node* InNode)
	{
		GraphNode = InNode;
		UpdateGraphNode();
	}

	struct IconDesc
	{
		int pinIndex;
		int (*selector)(UGCFSMTriggerEventNode*);
		void (*toggleValue)(UGCFSMTriggerEventNode*);
		FName icons[3];
		FText texts[3];

		const FSlateBrush* GetIcon(UGCFSMTriggerEventNode* node) const
		{
			static FName styleSetName { "GCFSM" };
			static FName styleDynamic { "Policy.ManagedByPin" };
			bool dynamic = node->Pins[pinIndex]->LinkedTo.Num() > 0;
			return FSlateIcon(styleSetName, dynamic ? styleDynamic : icons[selector(node)]).GetIcon();
		}

		FText ToolTipText(UGCFSMTriggerEventNode* node) const
		{
			bool dynamic = node->Pins[pinIndex]->LinkedTo.Num() > 0;
			return dynamic ? LOCTEXT("ManagedByPin", "This policy is managed dynamically by the value of the attached pin") : texts[selector(node)];
		}

		FReply OnMouseButtonDown(const FGeometry&, const FPointerEvent&, UGCFSMTriggerEventNode* node) const
		{
			auto pin = node->Pins[pinIndex];
			bool dynamic = pin->LinkedTo.Num() > 0;
			if (!dynamic && toggleValue)
			{
				FScopedTransaction _ { LOCTEXT("TogglePolicy", "Changed Trigger Event Policy") };
				node->Modify();
				toggleValue(node);
				node->SyncPinWithProperty(pin);
			}
			return FReply::Handled();
		}
	};

	template <class T>
	static T nextValue(T& x, int max)
	{
		return x = static_cast<T>((static_cast<int>(x) + 1) % max);
	}

	static bool nextValue(bool& x)
	{
		return x = !x;
	}

	static const std::array<IconDesc, 5>& GetIconDescriptions()
	{
		static std::array<IconDesc, 5> descriptions { {
			{
				UGCFSMTriggerEventNode::TargetPolicyPinIndex,
				[](UGCFSMTriggerEventNode* node) { return node->ShouldHideTargetPolicy() ? 0 : static_cast<int>(node->targetPolicy); },
				[](UGCFSMTriggerEventNode* node) { if (!node->ShouldHideTargetPolicy()) nextValue(node->targetPolicy, 2); },
				{ "TargetPolicy.Context", "TargetPolicy.State" },
				{
					LOCTEXT("TP_Context", "The effective target is the Context object of the target object"),
					LOCTEXT("TP_Target", "The effective target is the target object"),
				}
			},
			{
				UGCFSMTriggerEventNode::PropagatePolicyPinIndex,
				[](UGCFSMTriggerEventNode* node) { return static_cast<int>(node->propagateToSubstates); },
				[](UGCFSMTriggerEventNode* node) { nextValue(node->propagateToSubstates); },
				{ "PropagatePolicy.NoSubstates", "PropagatePolicy.Substates" },
				{
					LOCTEXT("PP_NoSubstates", "The event is triggered only on the effective target"),
					LOCTEXT("PP_Substates", "The event is triggered on the effective target and all active states of its FSMs, recursively"),
				}
			},
			{
				UGCFSMTriggerEventNode::TriggerInternalPolicyPinIndex,
				[](UGCFSMTriggerEventNode* node) { return static_cast<int>(node->triggerInternalEvents); },
				[](UGCFSMTriggerEventNode* node) { nextValue(node->triggerInternalEvents); },
				{ "InternalEventPolicy.Disallow", "InternalEventPolicy.Allow" },
				{
					LOCTEXT("IE_Disallowed", "Internal events are NOT triggered"),
					LOCTEXT("IE_Allowed", "Internal events are triggered"),
				}
			},
			{
				UGCFSMTriggerEventNode::QueuePolicyPinIndex,
				[](UGCFSMTriggerEventNode* node) { return static_cast<int>(node->queuePolicy); },
				[](UGCFSMTriggerEventNode* node) { nextValue(node->queuePolicy, 3); },
				{ "QueuePolicy.JustQueue", "QueuePolicy.KeepFirst", "QueuePolicy.KeepLast" },
				{
					LOCTEXT("QP_JustQueue", "Multiple such events are allowed in the queue"),
					LOCTEXT("QP_KeepFirst", "Only one such event is allowed in the queue: keep the first one"),
					LOCTEXT("QP_KeepLast", "Only one such event is allowed in the queue: keep the last one"),
				}
			},
			{
				UGCFSMTriggerEventNode::ExpireAfterPinIndex,
				[](UGCFSMTriggerEventNode* node) { return node->expireAfter > 0 ? 1 : 0; },
				nullptr,
				{ "ExpirePolicy.NoExpiration", "ExpirePolicy.WithExpiration" },
				{
					LOCTEXT("EP_NoExpiration", "The event has no expiration"),
					LOCTEXT("EP_Expiration", "The event expires after some time"),
				}
			}
		} };
		return descriptions;
	}

	void CreateBelowPinControls(TSharedPtr<SVerticalBox> MainBox) override
	{
		SGraphNodeK2Base::CreateBelowPinControls(MainBox);

		auto node = CastChecked<UGCFSMTriggerEventNode>(GraphNode);

		auto box = SNew(SHorizontalBox);
		for (auto& icon : GetIconDescriptions())
		{
			box.Get().AddSlot()
				.AutoWidth()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.Padding(FMargin(0, 0, 8, 0))
				[
					SNew(SImage)
					.Image_Raw(&icon, &IconDesc::GetIcon, node)
					.ToolTipText_Raw(&icon, &IconDesc::ToolTipText, node)
					.OnMouseButtonDown_Raw(&icon, &IconDesc::OnMouseButtonDown, node)
					.IsEnabled(this, &SGraphNodeK2Base::IsNodeEditable)
				];
		}

		// HACK: put my control above the ErrorReporting widget, not below
		int index = INDEX_NONE;
		if (ErrorReporting.IsValid())
		{
			index = MainBox->NumSlots() - 1;
		}

		MainBox->InsertSlot(index)
			.AutoHeight()
			.VAlign(VAlign_Fill)
			.Padding(FMargin(10, 0, 10, 10))
			[
				box
			];
	}
};

TSharedPtr<SGraphNode> UGCFSMTriggerEventNode::CreateVisualWidget()
{
	return SNew(VisualWidget, this);
}

#undef LOCTEXT_NAMESPACE
