// Copyright (c) 2018 Gamecentric, All rights reserved

#include "GCFSMFunctionWrapperNode.h"
#include "GCFSMUtilities.h"
#include "EdGraphSchema_K2.h"
#include "KismetCompiler.h"
#include "K2Node_CallFunction.h"

#define LOCTEXT_NAMESPACE "GCFSM.FunctionWrapperNode"

void UGCFSMFunctionWrapperNode::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	auto schema = GetDefault<UEdGraphSchema_K2>();
	int pinIndex = NextPinIndex;
	auto function = GetFunction();
	for (TFieldIterator<FProperty> it(function); it && (it->PropertyFlags & CPF_Parm); ++it)
	{
		auto prop = *it;
		if (prop->GetName() != TEXT("stateOrContext"))
		{
			FEdGraphPinType pinType;
			if (schema->ConvertPropertyToPinType(prop, pinType))
			{
				auto dir = (prop->PropertyFlags & (CPF_ReturnParm | CPF_OutParm)) ? EGPD_Output : EGPD_Input;
				auto pin = CreatePin(dir, pinType.PinCategory, pinType.PinSubCategory, pinType.PinSubCategoryObject.Get(), prop->GetFName());
				if (dir == EGPD_Input)
				{
					FString defaultValue;
					schema->FindFunctionParameterDefaultValue(function, prop, defaultValue);
					schema->SetPinAutogeneratedDefaultValue(pin, defaultValue);
				}
				++pinIndex;
			}
		}
	}
}

FSlateIcon UGCFSMFunctionWrapperNode::GetIconAndTint(FLinearColor& outColor) const
{
	return FSlateIcon("GCFSM", "NodeIcon.FunctionWrapper");
}

FText UGCFSMFunctionWrapperNode::GetNodeTitle(ENodeTitleType::Type titleType) const
{
	if (titleType != ENodeTitleType::FullTitle)
	{
		return GetNodeTitle();
	}
	else
	{
		UClass* targetClass = GetEffectiveTargetClass();
		FFormatNamedArguments Args;
		Args.Add(TEXT("Title"), GetNodeTitle());
		Args.Add(TEXT("Target"), targetClass->GetDisplayNameText());
		if (TargetIsContext() && targetClass->IsChildOf<UGCFSMState>())
		{
			return FText::Format(LOCTEXT("FullTitle", "{Title}\nTarget is {Target}'s Context"), Args);
		}
		else
		{
			return FText::Format(LOCTEXT("FullTitle", "{Title}\nTarget is {Target}"), Args);
		}
	}
}

void UGCFSMFunctionWrapperNode::ExpandNode(FKismetCompilerContext& compilerContext, UEdGraph* sourceGraph)
{
	Super::ExpandNode(compilerContext, sourceGraph);

	auto callFunction = compilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, sourceGraph);
	callFunction->SetFromFunction(GetFunction());
	callFunction->AllocateDefaultPins();
	compilerContext.MovePinLinksToIntermediate(*Pins[InExecPinIndex], *callFunction->GetExecPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[OutExecPinIndex], *callFunction->GetThenPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[TargetPinIndex], *callFunction->FindPinChecked(TEXT("stateOrContext")));

	for (int pinIndex = NextPinIndex; pinIndex < Pins.Num(); ++pinIndex)
	{
		auto pin = Pins[pinIndex];
		compilerContext.MovePinLinksToIntermediate(*pin, *callFunction->FindPinChecked(pin->PinName));
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
