// Copyright (c) 2018 Gamecentric, All rights reserved

#include "GCFSMLaunchNode.h"
#include "GCFSMEditorModule.h"
#include "GCFSMUtilities.h"
#include "GCFSMEditorUtilities.h"
#include "GCFSMReplicationComponent.h"
#include "EnumHelpers.h"
#include "EdGraphSchema_K2.h"
#include "KismetCompiler.h"
#include "K2Node_CallFunction.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/SCS_Node.h"

ENUM_HELPERS_NAME(EGCFSMReplicationOptions, GCFSM);

#define LOCTEXT_NAMESPACE "GCFSM.LaunchFSMNode"

void UGCFSMLaunchNode::AllocateDefaultPins()
{
	auto schema = GetDefault<UEdGraphSchema_K2>();

	Super::AllocateDefaultPins();

	check(Pins.Num() == ReplicationOptionsPinIndex);
	auto pin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, {}, EnumHelpers::GetUEnum<EGCFSMReplicationOptions>(), "replication");
	schema->SetPinAutogeneratedDefaultValueBasedOnType(pin);
}

void UGCFSMLaunchNode::PostPlacedNewNode()
{
	Super::PostPlacedNewNode();
	SyncAllPins();
}

void UGCFSMLaunchNode::PostReconstructNode()
{
	SyncAllPins();
	Super::PostReconstructNode();
}

void UGCFSMLaunchNode::PinDefaultValueChanged(UEdGraphPin* pin)
{
	Super::PinDefaultValueChanged(pin);
	SyncPropertyWithPin(pin);
}

void UGCFSMLaunchNode::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	Super::PostEditChangeProperty(propertyChangedEvent);

	if (propertyChangedEvent.Property)
	{
		SyncPinWithProperty(propertyChangedEvent.Property);

		if (const UEdGraphSchema* Schema = GetSchema())
		{
			Schema->ForceVisualizationCacheClear();
		}
	}
}

FSlateIcon UGCFSMLaunchNode::GetIconAndTint(FLinearColor& outColor) const
{
	return FSlateIcon("GCFSM", "NodeIcon.LaunchFSM");
}

FName UGCFSMLaunchNode::GetCornerIcon() const
{
	if (Pins.Num() > ReplicationOptionsPinIndex && (Pins[ReplicationOptionsPinIndex]->LinkedTo.Num() > 0 || Pins[ReplicationOptionsPinIndex]->DefaultValue != TEXT("NonReplicated")))
	{
		return "Graph.Replication.AuthorityOnly";
	}
	return NAME_None;
}

FText UGCFSMLaunchNode::GetNodeTitle(ENodeTitleType::Type titleType) const
{
	if (titleType != ENodeTitleType::FullTitle)
	{
		return LOCTEXT("NodeTitle", "Launch FSM");
	}
	else
	{
		FFormatNamedArguments Args;
		Args.Add(TEXT("Target"), GetEffectiveTargetClass()->GetDisplayNameText());
		return FText::Format(LOCTEXT("FullTitle", "Launch FSM\nTarget is {Target}"), Args);
	}
}

FText UGCFSMLaunchNode::GetTooltipText() const
{
	return LOCTEXT("ToolTip", "Launches the execution of an FSM in the target context or a sub-FSM in the target state object");
}

namespace
{
	template <class T>
	USCS_Node* GetSCSNode(UClass* actorClass)
	{
		if (auto blueprint = Cast<UBlueprint>(actorClass->ClassGeneratedBy))
		{
			for (auto scsNode : blueprint->SimpleConstructionScript->GetAllNodes())
			{
				if (scsNode->ComponentClass == T::StaticClass())
				{
					return scsNode;
				}
			}

			if (blueprint->ParentClass)
			{
				return GetSCSNode<T>(blueprint->ParentClass);
			}
		}
		return nullptr;
	}
}

void UGCFSMLaunchNode::ExpandNode(FKismetCompilerContext& compilerContext, UEdGraph* sourceGraph)
{
	Super::ExpandNode(compilerContext, sourceGraph);

	if (Pins[ReplicationOptionsPinIndex]->LinkedTo.Num() > 0 || Pins[ReplicationOptionsPinIndex]->DefaultValue != TEXT("NonReplicated"))
	{
		auto targetClass = GetEffectiveTargetClass();
		if (auto contextClass = targetClass && targetClass->IsChildOf<UGCFSMState>() ? UGCFSMState::GetContextClassForClass(targetClass) : targetClass)
		{
			if (contextClass->IsChildOf<AActor>() == false)
			{
				compilerContext.MessageLog.Warning(TEXT("The context object of @@ is not an actor. Replication will fail at runtime."), this);
			}
			else if (GetSCSNode<UGCFSMReplicationComponent>(contextClass) == nullptr)
			{
				compilerContext.MessageLog.Warning(TEXT("The context actor of @@ doesn't have a GC FSM Replication Component. Replication will fail at runtime."), this);
			}
		}
		else
		{
			compilerContext.MessageLog.Warning(TEXT("Couldn't determine context object of @@. Replication may fail at runtime."), this);
		}
	}

	auto callFunction = compilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, sourceGraph);
	callFunction->SetFromFunction(UGCFSMUtilities::StaticClass()->FindFunctionByName(TEXT("LaunchFSM")));
	callFunction->AllocateDefaultPins();
	compilerContext.MovePinLinksToIntermediate(*Pins[InExecPinIndex], *callFunction->GetExecPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[OutExecPinIndex], *callFunction->GetThenPin());
	compilerContext.MovePinLinksToIntermediate(*Pins[TargetPinIndex], *callFunction->FindPinChecked(TEXT("stateOrContext")));
	compilerContext.MovePinLinksToIntermediate(*Pins[NamePinIndex], *callFunction->FindPinChecked(TEXT("fsmName")));
	compilerContext.MovePinLinksToIntermediate(*Pins[ReplicationOptionsPinIndex], *callFunction->FindPinChecked(TEXT("replicationOptions")));
	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
